// <auto-generated />
using System;
using LearningLms.Modules.Scorm.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Host.Migrations.Scorm
{
    [DbContext(typeof(ScormDbContext))]
    partial class ScormDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("LearningLms.Modules.Scorm.Domain.ScormPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentDirectory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LaunchPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManifestTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("ScormPackages");
                });

            modelBuilder.Entity("LearningLms.Modules.Scorm.Domain.CourseAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastCommitAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("ScoreRaw")
                        .HasColumnType("float");

                    b.Property<string>("SessionTime")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SuspendData")
                        .HasMaxLength(65536)
                        .HasColumnType("nvarchar(65536)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "CourseId", "AttemptNumber")
                        .IsUnique();

                    b.HasIndex("StudentId", "CourseId");

                    b.ToTable("CourseAttempts");
                });
        }
    }
}
